// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLyVsclWeM9kPiSLhfkvzezpoYrAFWII',
    appId: '1:135211312783:web:128bba58e3d5806a6ef2fa',
    messagingSenderId: '135211312783',
    projectId: 'flutterj-4cda4',
    authDomain: 'flutterj-4cda4.firebaseapp.com',
    storageBucket: 'flutterj-4cda4.firebasestorage.app',
    measurementId: 'G-NRRZQWSS8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_wQ2IQ70OBz2y7hLIBrWGZPa5bRaa9ss',
    appId: '1:135211312783:android:ed0b7e9260918e866ef2fa',
    messagingSenderId: '135211312783',
    projectId: 'flutterj-4cda4',
    storageBucket: 'flutterj-4cda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DHAbdRdSYMQ5xevsr8NXoTMZeOcuNMI',
    appId: '1:135211312783:ios:5a3e999c625077716ef2fa',
    messagingSenderId: '135211312783',
    projectId: 'flutterj-4cda4',
    storageBucket: 'flutterj-4cda4.firebasestorage.app',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3DHAbdRdSYMQ5xevsr8NXoTMZeOcuNMI',
    appId: '1:135211312783:ios:5a3e999c625077716ef2fa',
    messagingSenderId: '135211312783',
    projectId: 'flutterj-4cda4',
    storageBucket: 'flutterj-4cda4.firebasestorage.app',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNLyVsclWeM9kPiSLhfkvzezpoYrAFWII',
    appId: '1:135211312783:web:398567d30daf14766ef2fa',
    messagingSenderId: '135211312783',
    projectId: 'flutterj-4cda4',
    authDomain: 'flutterj-4cda4.firebaseapp.com',
    storageBucket: 'flutterj-4cda4.firebasestorage.app',
    measurementId: 'G-N11R6534XM',
  );
}
